/**
 * Def Jam: Fight for NY (Xbox, EA-073) - Recompiled Game Entry Point
 *
 * This is the executable that hosts the recompiled game code.
 * It performs the following initialization sequence:
 *
 * 1. Load the original XBE file from disk
 * 2. Initialize the Xbox memory layout (map data sections to original VAs)
 * 3. Initialize the Xbox kernel replacement layer
 * 4. Initialize the kernel bridge (thunk table in Xbox memory)
 * 5. Set up game file paths for I/O redirection
 * 6. Initialize the stack pointer
 * 7. Install VEH crash handler for diagnostics
 * 8. Call the game's original entry point (recompiled)
 *
 * Customize this file for your game:
 *   - Set YOUR_GAME_ENTRY_POINT to the XBE entry point address
 *   - Set YOUR_GAME_XBE_PATH to where the XBE file lives
 *   - Set YOUR_GAME_DIR to the game data directory
 *   - Add any CRT global pre-initialization your game needs
 *   - Customize the VEH handler for game-specific crash diagnosis
 *
 * XBE Details (fill in from xbe_parser output):
 *   Title:       DJFFNY (Def Jam: Fight for NY, USA)
 *   Title ID:    0x45410049 (EA-073)
 *   Base addr:   0x00010000
 *   Entry point: 0x001F6357
 *   Code size:   2,096,628 bytes (.text), 16,051 functions
 *   Sections:    12 (.text XGRPH D3D D3DX DSOUND XPP .rdata .data DOLBY $$XTIMAGE DISCERROR_E DISCERROR_F)
 *   Kernel imports: 160 (XDK 5849)
 */

#include "host.h"
#if defined(_WIN32)
#include <dbghelp.h>
#else
#include <dlfcn.h>
#if defined(__APPLE__)
#include <mach-o/getsect.h>
#include <mach-o/ldsyms.h>
#endif
#include <signal.h>
#include <unistd.h>
#endif
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>

/* xboxrecomp runtime headers */
#include <xbox/xboxrecomp.h>
#include "nv2a/nv2a_pgraph_d3d11.h"
#include "hooks/save_compat.h"

/*
 * If xboxrecomp.h is not an umbrella header in your setup, include
 * the individual headers directly:
 *
 * #include "kernel.h"
 * #include "xbox_memory_layout.h"
 * #include "d3d8_xbox.h"
 * #include "dsound_xbox.h"
 * #include "xinput_xbox.h"
 */

/* ── Global register state (defined in xbox_memory_layout.c) ── */

/* RECOMP_TLS is not optional here. The runtime defines these thread-local, and
 * a plain `extern` referencing a __declspec(thread) variable does not resolve
 * to the calling thread's copy -- it resolves to the image's TLS template. The
 * host side then writes g_esp somewhere the generated code never reads, so the
 * guest starts with every register at zero and faults immediately, having
 * apparently ignored the setup that visibly ran. */
extern RECOMP_TLS uint32_t g_eax, g_ecx, g_edx, g_esp;
extern RECOMP_TLS uint32_t g_ebx, g_esi, g_edi;
extern RECOMP_TLS uint32_t g_seh_ebp;
/* x87 and SSE state. Global for the same reason the volatile GPRs are: one
 * guest routine can lift to several C functions, so a value written in one
 * body is read in the next. Defined in xbox_memory_layout.c like the rest of
 * the register file. */
extern RECOMP_TLS double g_fp_stack[8];
extern RECOMP_TLS int g_fp_top;
extern RECOMP_TLS uint16_t g_fp_control_word;
extern RECOMP_TLS int g_fp_cmp;
extern RECOMP_TLS RecompXmm g_xmm0, g_xmm1, g_xmm2, g_xmm3;
extern RECOMP_TLS RecompXmm g_xmm4, g_xmm5, g_xmm6, g_xmm7;
extern ptrdiff_t g_xbox_mem_offset;

/* ── XBE Constants ─────────────────────────────────────────── */

/*
 * TODO: Set these from your xbe_parser output.
 * Run: py -3 -m tools.xbe_parser game/default.xbe
 */
#define YOUR_GAME_ENTRY_POINT   0x001F6357  /* XBE entry point VA */
#define YOUR_GAME_XBE_PATH      "game/default.xbe"   /* forward slashes: fine for CreateFile/fopen */
#define YOUR_GAME_DIR            "game"

/* ── Forward declarations ──────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size);
int pc_settings_init(void);   /* src/hooks/pc_settings.c */
void pc_settings_set_args(int argc, char **argv);

/* Recompiled entry point (generated by recomp pipeline) */
extern void xbe_entry_point(void);

/* ── Emulated devices the guest drives through its own registers ──
 *
 * Declared here rather than by including the runtime's private headers: those
 * pull in the QEMU compatibility shims the APU model is written against, and
 * a pointer plus three entry points is the whole interface this program needs.
 */
struct MCPXAPUState;
extern struct MCPXAPUState *g_apu_state;                /* set by the init below */
struct MCPXAPUState *mcpx_apu_init_standalone(unsigned char *ram_ptr);
bool apu_hook_handle_mmio(PCONTEXT ctx, uintptr_t fault_addr,
                          uint32_t fault_xbox_va, int is_write);

void xbox_OhciInit(void);                               /* self-gated on RECOMP_USB */
int  xbox_OhciOwnsAddress(uint32_t xbox_va);
int  xbox_OhciHandleMmio(void *ctx, uint32_t xbox_va);

/* src/hooks/ac97_bm.c: the audio controller's bus-master registers, trapped so
 * a channel reset can report itself finished. See that file for why memory
 * cannot answer this one. */
void ac97_bm_init(ptrdiff_t mem_offset);
int  ac97_bm_owns_address(uint32_t xbox_va);
int  ac97_bm_handle_mmio(void *ctx, uint32_t xbox_va);
void ac97_bm_report(void);
void nv2a_regs_init(ptrdiff_t mem_offset);
int  nv2a_regs_owns_address(uint32_t xbox_va);
int  nv2a_regs_handle_mmio(void *ctx, uint32_t xbox_va);
void nv2a_regs_report(void);
int  watchpoint_init(void);
int  postcmd_init(void);
int  codeguard_init(void);
int  watchpoint_handle_trap(void *ctx);

/* src/hooks/d3d11_translator.c: a D3D11 device and window for the push-buffer
 * translator, which the title's own statically linked Direct3D never creates. */
int  d3d11_translator_init(void);
void d3d11_translator_pump(void);
void d3d11_translator_frame_end(void);

/* ── VEH crash handler ─────────────────────────────────────── */

/*
 * Vectored Exception Handler for crash diagnostics.
 *
 * When the recompiled game hits an access violation, this handler prints
 * the faulting address, all Xbox register values, and a native stack trace.
 * This is your primary debugging tool during bring-up.
 *
 * Customize this for your game:
 *   - Add game-specific address checks (GPU register probes, etc.)
 *   - Add dumps of game-specific globals (heap handles, state flags)
 *   - Add SEH simulation if your game uses __try/__except
 */
/* Name the guest function a fault happened in, and recover the call chain.
 *
 * Recompiled code faults as ordinary native code, so the exception record
 * carries a host RIP and nothing else -- there is no guest program counter to
 * report, and the host address changes every build. Two things recover the
 * guest view:
 *
 *   - every generated function is a real symbol in the image (sub_005A03C0
 *     and so on), so the linker's PDB already maps host address back to guest
 *     function. dbghelp turns an anonymous RIP into that name.
 *
 *   - every lifted call pushes its guest return address onto the guest stack
 *     before jumping, so the stack still holds the chain. Scanning up from esp
 *     for values inside the code sections recovers it.
 *
 * ponytail: the stack scan is a scan, not a frame walk -- these are FPO frames
 * with no reliable ebp chain, so there is nothing to walk. It over-reports,
 * since addresses from returned-from calls linger below esp, but naming the
 * guest function is the whole question at a fault.
 *
 * Requires linking dbghelp and keeping the .pdb beside the .exe.
 */
static void print_guest_context(void *rip)
{
#if defined(_WIN32)
    /* SYMBOL_INFO is variable-length: the name is written past the struct, so
     * it must be over-allocated with MaxNameLen set to the slack. */
    char buf[sizeof(SYMBOL_INFO) + 256];
    SYMBOL_INFO *sym = (SYMBOL_INFO *)buf;
    DWORD64 disp = 0;

    memset(buf, 0, sizeof(buf));
    sym->SizeOfStruct = sizeof(SYMBOL_INFO);
    sym->MaxNameLen = 255;
    if (SymFromAddr(GetCurrentProcess(), (DWORD64)(uintptr_t)rip, &disp, sym))
        fprintf(stderr, "  in %s+0x%llX\n",
                sym->Name, (unsigned long long)disp);
#else
    /* The generated functions are ordinary symbols here too; the dynamic
     * loader's table names them as long as the link exports them. */
    Dl_info info;

    if (dladdr(rip, &info) && info.dli_sname)
        fprintf(stderr, "  in %s+0x%llX\n", info.dli_sname,
                (unsigned long long)((uintptr_t)rip - (uintptr_t)info.dli_saddr));
#endif

    /* What the pointer registers were actually pointing at.
     *
     * A fault through a structure field is the common shape here, and the
     * registers alone never say which field: they give the object, not its
     * contents. Dumping a little of each pointed-to object turns "esi was
     * 0xFFFFFFFF" into "this field of that object was never written", which
     * is the question. Each read is bounds-checked because at least one of
     * these registers is wild by definition at a fault. */
    if (g_xbox_mem_offset) {
        static const char *const names[] = { "eax", "ecx", "edx", "ebx", "esi", "edi" };
        const uint32_t regs[] = { g_eax, g_ecx, g_edx, g_ebx, g_esi, g_edi };
        size_t r;

        fprintf(stderr, "  guest memory at the pointer registers:\n");
        for (r = 0; r < sizeof(regs) / sizeof(regs[0]); r++) {
            uint32_t va = regs[r];
            int w;
            if (va < XBOX_BASE_ADDRESS || (uint64_t)va + 32 > XBOX_TOTAL_RAM) {
                fprintf(stderr, "    %s 0x%08X  (not a guest pointer)\n",
                        names[r], va);
                continue;
            }
            fprintf(stderr, "    %s 0x%08X ->", names[r], va);
            for (w = 0; w < 8; w++)
                fprintf(stderr, " %08X",
                        *(const uint32_t *)((uintptr_t)g_xbox_mem_offset + va + w * 4));
            fprintf(stderr, "\n");
        }
    }

    if (g_xbox_mem_offset && g_esp) {
        const uint32_t *sp =
            (const uint32_t *)((uintptr_t)g_xbox_mem_offset + g_esp);
        int shown = 0, i;
        fprintf(stderr, "  guest stack (scan, not a walk -- includes stale frames):\n");
        for (i = 0; i < 256 && shown < 24; i++) {
            uint32_t v = sp[i];
            if (v > g_xbox_code_lo && v < g_xbox_code_hi) {
                fprintf(stderr, "    [esp+%-4d] 0x%08X\n", i * 4, v);
                shown++;
            }
        }
    }
}


/* ---- Does the lifted CRT still divide correctly? ----------------------
 *
 * The recompiler used to drop `rcr`, which is the instruction MSVC's 64-bit
 * divide helpers use to shift a 64-bit pair one bit right. Without it the
 * shift happened on one half and the bit that should have crossed vanished,
 * so _alldiv, _aulldiv, _allrem and _aullrem were all silently wrong whenever
 * the divisor did not fit in 32 bits. Silently is the problem: nothing faults,
 * a number is simply not the number.
 *
 * So the four of them are exercised against answers computed here, on the way
 * up, with operands that force the path that uses `rcr`. Off unless
 * RECOMP_SELFTEST is set, because it costs a few microseconds and the answer
 * only changes when the lifter does -- but run it after any lifter change.
 *
 * The guest calling convention is the one the generated code uses: push the
 * arguments right to left, push a return address, call, and read the result
 * out of the guest edx:eax. The callees are __stdcall, so they clean up.
 */
typedef void (*recomp_func_t)(void);
/* Guest memory, the same translation the generated code uses. Spelled out
 * here rather than including recomp_types.h, which would drag the whole
 * register model into a file that only needs four stack pushes. */
#define GUEST32(va) (*(volatile uint32_t *)((uintptr_t)(va) + (uintptr_t)g_xbox_mem_offset))
extern recomp_func_t recomp_lookup(uint32_t xbox_va);
int recomp_dispatch_init(void);   /* generated, recomp_dispatch.c */

static void recomp_selftest(void)
{
    /* The four helpers that contain `rcr`, by address. Which of them is the
     * quotient and which the remainder is not asserted here: the first attempt
     * guessed, got one wrong, and reported a correct function as broken. The
     * test instead accepts either answer and says which it saw, so it is
     * checking arithmetic rather than a naming hunch. */
    static const uint32_t helpers[] = {
        0x00201470u, 0x00202930u, 0x002032C0u, 0x00209630u,
    };
    /* A divisor above 2^32 is what takes the rcr path. Both operands are
     * positive, so the signed and unsigned helpers agree. */
    const uint64_t dividend = 0x0000123456789ABCull;
    const uint64_t divisor  = 0x0000000100000007ull;
    const uint64_t quotient = dividend / divisor;
    const uint64_t remainder = dividend % divisor;
    size_t i;
    int bad = 0;

    if (!getenv("RECOMP_SELFTEST"))
        return;

    for (i = 0; i < sizeof(helpers) / sizeof(helpers[0]); i++) {
        recomp_func_t fn = recomp_lookup(helpers[i]);
        uint32_t saved_esp = g_esp;
        uint64_t got;

        if (!fn) {
            fprintf(stderr, "  [SELFTEST] 0x%08X is not in the dispatch table\n",
                    helpers[i]);
            bad++;
            continue;
        }

        g_esp -= 4; GUEST32(g_esp) = (uint32_t)(divisor >> 32);
        g_esp -= 4; GUEST32(g_esp) = (uint32_t)divisor;
        g_esp -= 4; GUEST32(g_esp) = (uint32_t)(dividend >> 32);
        g_esp -= 4; GUEST32(g_esp) = (uint32_t)dividend;
        g_esp -= 4; GUEST32(g_esp) = 0;        /* return address, unused */
        fn();
        got = ((uint64_t)g_edx << 32) | g_eax;
        g_esp = saved_esp;

        if (got == quotient || got == remainder) {
            fprintf(stderr, "  [SELFTEST] 0x%08X -> %s, correct\n", helpers[i],
                    got == quotient ? "quotient" : "remainder");
        } else {
            fprintf(stderr, "  [SELFTEST] 0x%08X(0x%llX, 0x%llX) = 0x%llX, "
                            "neither the quotient 0x%llX nor the remainder "
                            "0x%llX\n", helpers[i],
                    (unsigned long long)dividend, (unsigned long long)divisor,
                    (unsigned long long)got, (unsigned long long)quotient,
                    (unsigned long long)remainder);
            bad++;
        }
    }
    fprintf(stderr, "  SELFTEST: 64-bit divide helpers %s\n",
            bad ? "FAILED" : "all correct");

    /* The CRT's x87 fmod intrinsic, _CIfmod (0x0020144E): arguments on the
     * register stack, x in st(1) and y in st(0); the result replaces them, one
     * slot shallower. APT reduces angles with it when it decomposes a clip's
     * matrix (sub_00164920), and wrong scale and rotation came out of that. */
    {
        recomp_func_t fn = recomp_lookup(0x0020144Eu);
        uint32_t saved_esp = g_esp;
        int top0 = g_fp_top;
        /* The values APT feeds it: atan2 of an identity matrix is 0 (or -0),
        * reduced modulo pi. Zero takes the CRT's special-value path. */
        static const double xs[] = { 7.5, 0.0, -0.0, 1.5707963705062866 };
        const double y = 3.1415927410125732;
        uint32_t flag_saved = GUEST32(0x002FAD20u);   /* the CRT picks its path on this */
        int pass, k;
        for (pass = 0; pass < 2 && fn; pass++)
        for (k = 0; k < 4; k++) {
            const double x = xs[k];
            GUEST32(0x002FAD20u) = (uint32_t)pass;
            top0 = g_fp_top;
            g_fp_top = (g_fp_top + 7) & 7; g_fp_stack[g_fp_top] = x;
            g_fp_top = (g_fp_top + 7) & 7; g_fp_stack[g_fp_top] = y;
            g_esp -= 4; GUEST32(g_esp) = 0;    /* return address, unused */
            fn();
            fprintf(stderr, "  [SELFTEST] _CIfmod(%g, %g) [flag %d] = %g (expected %g); net x87 depth %d (expected 1)\n",
                    x, y, pass, g_fp_stack[g_fp_top], fmod(x, y), (top0 - g_fp_top) & 7);
            g_esp = saved_esp;
            g_fp_top = top0;
        }
        GUEST32(0x002FAD20u) = flag_saved;
    }
    fflush(stderr);
}

void host_fatal(const char *message)
{
#if defined(_WIN32)
    MessageBoxA(NULL, message, "Def Jam: Fight for NY", MB_ICONERROR);
#else
    fprintf(stderr, "Def Jam: Fight for NY: %s\n", message);
    fflush(stderr);
#endif
}

#if defined(_WIN32)
static LONG CALLBACK veh_handler(PEXCEPTION_POINTERS ep)
{
    /* A hardware watchpoint arrives as a single step. Answered before anything
     * else because it is not a fault: the instruction completed, and all this
     * does is say which instruction it was. See src/hooks/watchpoint.c. */
    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_SINGLE_STEP) {
        if (watchpoint_handle_trap(ep->ContextRecord))
            return EXCEPTION_CONTINUE_EXECUTION;
    }

    if (ep->ExceptionRecord->ExceptionCode == EXCEPTION_ACCESS_VIOLATION) {
        uintptr_t fault_addr = ep->ExceptionRecord->ExceptionInformation[1];
        uint32_t  fault_va   = (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset);
        int       is_write   = ep->ExceptionRecord->ExceptionInformation[0] != 0;

        /*
         * Trapped device registers.
         *
         * The runtime backs most hardware apertures with plain memory, but the
         * two devices that have real models are deliberately left unmapped so
         * that touching them faults: that fault is how a guest access reaches
         * the model at all. Routing it is this program's job, not the
         * runtime's -- the handler has to run on the thread that faulted, and
         * only the host image owns the VEH chain. Without this the trap fires
         * and nothing answers it, which reads as a crash inside audio init.
         */
        if (g_apu_state && fault_va >= 0xFE800000u && fault_va < 0xFE880000u) {
            if (apu_hook_handle_mmio(ep->ContextRecord, fault_addr, fault_va, is_write))
                return EXCEPTION_CONTINUE_EXECUTION;
        }
        if (xbox_OhciOwnsAddress(fault_va)) {
            if (xbox_OhciHandleMmio(ep->ContextRecord, fault_va))
                return EXCEPTION_CONTINUE_EXECUTION;
        }
        if (ac97_bm_owns_address(fault_va)) {
            if (ac97_bm_handle_mmio(ep->ContextRecord, fault_va))
                return EXCEPTION_CONTINUE_EXECUTION;
        }
        /* Before the blanket 0xFD000000 skip below: one page of it is modelled
         * properly, and the skip would step over the flush handshake. */
        if (nv2a_regs_owns_address(fault_va)) {
            if (nv2a_regs_handle_mmio(ep->ContextRecord, fault_va))
                return EXCEPTION_CONTINUE_EXECUTION;
        }

        /*
         * GPU register probe at 0xFD000000 range.
         * Some games probe NV2A registers directly. On real hardware this
         * returns GPU state; here we just skip the instruction.
         * TODO: Implement mini x86-64 decoder for instruction skipping,
         * or connect to the xbox_nv2a library for proper handling.
         */
        if (fault_addr >= 0xFD000000 && fault_addr < 0xFE000000) {
            return EXCEPTION_CONTINUE_SEARCH;
        }

        fprintf(stderr, "[CRASH] Access violation at RIP=0x%llX, fault addr=0x%llX (%s)\n",
            (unsigned long long)ep->ContextRecord->Rip,
            (unsigned long long)fault_addr,
            ep->ExceptionRecord->ExceptionInformation[0] ? "write" : "read");
        fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
        fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
        fprintf(stderr, "  Xbox VA of fault: 0x%08X\n",
            (uint32_t)(fault_addr - (uintptr_t)g_xbox_mem_offset));
        print_guest_context((void *)ep->ContextRecord->Rip);

        /*
         * TODO: Add game-specific diagnostics here. Examples:
         *
         * Dump CRT heap handle:
         *   uint32_t heap = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + HEAP_HANDLE_VA);
         *   fprintf(stderr, "  CRT heap handle: 0x%08X\n", heap);
         *
         * Dump game state:
         *   uint32_t state = *(uint32_t *)((uint8_t *)g_xbox_mem_offset + GAME_STATE_VA);
         *   fprintf(stderr, "  Game state: %u\n", state);
         */

        /* Print native stack return addresses for debugging */
        {
            uintptr_t *sp = (uintptr_t *)ep->ContextRecord->Rsp;
            fprintf(stderr, "  Native stack (first 8 return addrs):\n");
            for (int i = 0; i < 64 && sp[i]; i++) {
                if (sp[i] >= 0x140000000ULL && sp[i] < 0x150000000ULL) {
                    fprintf(stderr, "    [%d] 0x%llX\n", i, (unsigned long long)sp[i]);
                }
            }
        }
        fflush(stderr);
    }

    return EXCEPTION_CONTINUE_SEARCH;
}

#else /* !_WIN32 */

/* The same routing from a signal handler. ctx is the ucontext; the device
 * models decode the faulting instruction through the runtime's trap layer.
 *
 * One addition over the Windows handler: where the host page is larger than
 * the console's 4 KB (16 KB on Apple Silicon), closing a device page closes
 * its neighbours, and an access to one of those is completed as memory. */
static void fault_handler(int sig, siginfo_t *si, void *ctx)
{
    uintptr_t fault_addr = (uintptr_t)si->si_addr;
    uintptr_t rel = fault_addr - (uintptr_t)g_xbox_mem_offset;

    if ((sig == SIGBUS || sig == SIGSEGV) && g_xbox_mem_offset && rel <= 0xFFFFFFFFu) {
        uint32_t fault_va = (uint32_t)rel;

        if (g_apu_state && fault_va >= 0xFE800000u && fault_va < 0xFE880000u
                && apu_hook_handle_mmio(ctx, fault_addr, fault_va, 0))
            return;
        if (xbox_OhciOwnsAddress(fault_va) && xbox_OhciHandleMmio(ctx, fault_va))
            return;
        if (ac97_bm_owns_address(fault_va) && ac97_bm_handle_mmio(ctx, fault_va))
            return;
        if (nv2a_regs_owns_address(fault_va) && nv2a_regs_handle_mmio(ctx, fault_va))
            return;
    }
    if ((sig == SIGBUS || sig == SIGSEGV) && mmio_trap_neighbour(ctx, fault_addr))
        return;

    fprintf(stderr, "[CRASH] %s (%s) at PC=0x%llX, fault addr=0x%llX\n",
            sig == SIGBUS || sig == SIGSEGV ? "Access violation" : "Fatal signal",
            sig == SIGBUS ? "SIGBUS" : sig == SIGSEGV ? "SIGSEGV" : sig == SIGILL ? "SIGILL"
            : sig == SIGTRAP ? "SIGTRAP" : sig == SIGFPE ? "SIGFPE" : sig == SIGABRT ? "SIGABRT" : "signal",
            (unsigned long long)HOST_PC(ctx), (unsigned long long)fault_addr);
    fprintf(stderr, "  Xbox regs: eax=0x%08X ecx=0x%08X edx=0x%08X esp=0x%08X\n",
            g_eax, g_ecx, g_edx, g_esp);
    fprintf(stderr, "  Xbox regs: ebx=0x%08X esi=0x%08X edi=0x%08X\n",
            g_ebx, g_esi, g_edi);
    if (g_xbox_mem_offset && rel <= 0xFFFFFFFFu)
        fprintf(stderr, "  Xbox VA of fault: 0x%08X\n", (uint32_t)rel);
    else
        fprintf(stderr, "  The fault address is outside guest memory\n");
    {
        const uint32_t *ip = (const uint32_t *)(uintptr_t)HOST_PC(ctx);
        Dl_info info;
        /* Only read the instruction if the address is inside a loaded image. */
        if (dladdr(ip, &info) && info.dli_fname)
            fprintf(stderr, "  host instruction: %08X\n", *ip);
    }
    print_guest_context((void *)(uintptr_t)HOST_PC(ctx));
    fflush(stdout);
    fflush(stderr);
    /* Put the default action back; the instruction faults again and the
     * process ends with the signal, as an unhandled exception would. */
    signal(sig, SIG_DFL);
}

static void install_fault_handler(void)
{
    struct sigaction sa;

    memset(&sa, 0, sizeof sa);
    sa.sa_sigaction = fault_handler;
    sa.sa_flags = SA_SIGINFO | SA_NODEFER;
    sigemptyset(&sa.sa_mask);
    sigaddset(&sa.sa_mask, SIGUSR2);   /* no guest-CPU hand-over inside a trap */
    /* Darwin reports a protection fault as SIGBUS, Linux as SIGSEGV. */
    sigaction(SIGSEGV, &sa, NULL);
    sigaction(SIGBUS, &sa, NULL);
    /* The ways a process dies without touching bad memory -- an abort in a
     * library, a trap the compiler planted, an illegal instruction -- so the
     * log says what happened instead of simply stopping. */
    sigaction(SIGILL, &sa, NULL);
    sigaction(SIGTRAP, &sa, NULL);
    sigaction(SIGFPE, &sa, NULL);
    sigaction(SIGABRT, &sa, NULL);
}

#endif /* _WIN32 */

/* ── Entry ─────────────────────────────────────────────────── */

#if defined(_WIN32)
int WINAPI WinMain(HINSTANCE hInstance, HINSTANCE hPrevInstance,
                   LPSTR lpCmdLine, int nCmdShow)
#else
static int host_main(void)
#endif
{
    void *xbe_data = NULL;
    size_t xbe_size = 0;

#if defined(_WIN32)
    (void)hInstance;
    (void)hPrevInstance;
    (void)lpCmdLine;
    (void)nCmdShow;
#endif

    /* Buffered, and flushed: by the 130-odd fflush calls after messages that
     * matter, by the crash handler, and once a second by the runtime's timer
     * thread.
     *
     * These were unbuffered "for immediate visibility", which redirected to a
     * file means one WriteFile per character. Every thread that logs holds the
     * stderr lock for the whole string, the GPU executor among them, so during
     * start-up -- the chattiest phase -- the title crawled at a frame every
     * second or so in some runs, with most of its threads queued on that lock
     * behind two writers doing single-character system calls. */
    setvbuf(stdout, NULL, _IOFBF, 1 << 16);
    setvbuf(stderr, NULL, _IOFBF, 1 << 16);

    /* Find the game folder, open a log if nothing captures the output, supply
     * the runtime's required switches and load settings.ini -- before anything
     * reads the environment. See src/hooks/pc_settings.c. */
    if (!pc_settings_init())
        return 1;

    printf("=== Def Jam: Fight for NY - Static Recompilation ===\n");
    printf("Loading XBE...\n");

    /* Install VEH handler (first handler in chain) */
    /* Load symbols up front rather than from inside the handler: at fault
     * time the process is already in a bad way, and SymInitialize
     * allocates. Failure is not fatal -- the handler prints no name. */
#if defined(_WIN32)
    SymSetOptions(SYMOPT_DEFERRED_LOADS | SYMOPT_UNDNAME);
    SymInitialize(GetCurrentProcess(), NULL, TRUE);
    AddVectoredExceptionHandler(1, veh_handler);
#else
    install_fault_handler();
#endif

    /* Step 1: Load XBE */
    if (!load_xbe(YOUR_GAME_XBE_PATH, &xbe_data, &xbe_size)) {
        host_fatal("Failed to load default.xbe.\n"
                   "Place the game files in the 'game' subdirectory.");
        return 1;
    }
    printf("XBE loaded: %zu bytes\n", xbe_size);

    /* Report the audio codec as present, before the layout is built.
     *
     * The title's DirectSound is statically linked into the XBE, so it was
     * recompiled along with the game and still programs the APU and AC'97
     * registers directly. Against zeroed registers the codec never reports
     * ready, DirectSoundCreate fails, and the object it should have produced
     * is left null -- which surfaces much later, and somewhere else, as a
     * fault through a pointer read back out of that null object.
     *
     * The same switch unmaps the APU's own 512 KB so accesses fault and can
     * reach the emulated device; this program's exception handler is what
     * carries them there, and the APU model is brought up below. Both halves
     * or neither, which is why one variable governs both. Still overridable:
     * set it to empty in the environment to get the old behaviour back. */
    if (!getenv("RECOMP_AC97_READY"))
        _putenv_s("RECOMP_AC97_READY", "1");

    /* Preserve this title's six-speaker balance when using the newer toolkit. */
    if (!getenv("RECOMP_APU_MIXDOWN"))
        _putenv_s("RECOMP_APU_MIXDOWN", "six");

    /* Acknowledge the audio DSP's command doorbell.
     *
     * DirectSound hands the DSP a command block in guest memory, writes a
     * command word, and spins until the DSP writes zero back. On hardware a
     * DSP56300 program does that. The emulated processor here is a passthrough
     * stub, so without this the word never changes and the title stops inside
     * audio initialisation, having drawn its loading screen and loaded twelve
     * files. With it, the same run loads thirty-three and issues thousands of
     * draw calls.
     *
     * The APU model now finds the doorbell itself (toolkit patch 0011): it is
     * at offset 0x810 of the GP scratch memory's first page, which the title
     * publishes through GPSADDR's scatter-gather table. This used to be a
     * fixed address observed with scripts/guest-regs.py (0x819E8810), which
     * went stale the moment the heap layout changed and then cleared a word
     * in the middle of the game's main arena every audio frame.
     * RECOMP_APU_DSP_ACK=<addr> still overrides the derivation.
     *
     * This acknowledges a handshake; it is not a DSP. Every command reports
     * instant success and computes nothing, so anything whose result the title
     * reads back is still wrong. Real DSP emulation is the actual fix. */

    /* Step 2: Initialize Xbox memory layout */
    printf("Initializing Xbox memory layout...\n");
    if (!xbox_MemoryLayoutInit(xbe_data, xbe_size)) {
        host_fatal("Failed to initialize Xbox memory layout.\n"
                   "The required virtual address range may be unavailable.");
        free(xbe_data);
        return 1;
    }

    g_xbox_mem_offset = xbox_GetMemoryOffset();

    /* Bring up the devices whose registers the guest drives itself. The APU
     * takes a native pointer to guest address zero, because the addresses it
     * is handed in command blocks are guest ones. The USB host controllers do
     * nothing unless RECOMP_USB is set: that model finds a port but has
     * nothing behind it yet, so it stays opt-in until it can carry a report. */
    g_apu_state = mcpx_apu_init_standalone((unsigned char *)g_xbox_mem_offset);
    if (!g_apu_state)
        fprintf(stderr, "[BOOT] APU model unavailable; audio registers will fault\n");
    xbox_OhciInit();
    /* After the codec-ready bit is set above, so the shadow inherits it. */
    ac97_bm_init(g_xbox_mem_offset);
    /* The GPU registers that cannot be plain memory: the write-back-cache
     * flush the title spins on, and the free-running clock. */
    nv2a_regs_init(g_xbox_mem_offset);

    /* Optional: watch one guest address for writes (RECOMP_WATCH_WRITE).
     * Must come after the memory layout exists, because it needs the offset. */
    watchpoint_init();
    postcmd_init();
    codeguard_init();

    /* Stand up a D3D11 device for the push-buffer translator, if asked. The
     * title never calls the runtime's Direct3D, so without this the translator
     * has nothing to draw through. See src/hooks/d3d11_translator.c. */
    /* Preserve the established harness's anchored seconds grammar. */
    if (!getenv("RECOMP_PAD_SCRIPT_FORMAT"))
        _putenv_s("RECOMP_PAD_SCRIPT_FORMAT", "seconds");
    d3d11_translator_init();
#ifdef RECOMP_PGRAPH_FRAME_END_CALLBACK
    pgraph_d3d11_set_frame_end_callback(d3d11_translator_frame_end);
#endif

    /* Optional: check the lifted CRT's 64-bit divides (RECOMP_SELFTEST). */
    recomp_selftest();

    /* Def Jam's D3D (XDK 5849) polls a GPU-written fence for pushbuffer space:
     * D3DDevice_MakeSpace at 0x0021EC50 spins on (Put - *GetPtr) where
     *   g_pDevice = [0x00234768], Put = [g_pDevice + 0x2C],
     *   GetPtr    = [g_pDevice + 0x30]  (-> 0x81202000, contiguous RAM).
     * Nothing here executes the pushbuffer asynchronously, so mirror Put into
     * *GetPtr every runtime tick; the buffer is consumed at submit anyway. */
    xbox_Nv2aMirrorFence(0x00234768u, 0x2Cu, 0x30u);
    printf("Xbox memory mapped. Offset: 0x%llX\n", (unsigned long long)g_xbox_mem_offset);

    /* Step 3: Initialize Xbox kernel */
    printf("Initializing Xbox kernel replacement...\n");
    xbox_kernel_init();

    /* Step 4: Set game directory for file I/O path translation.
     *
     * The save side is the title's writable storage: T:, U:, the cache
     * partitions, and TDATA on the hard disk, which is where this title puts
     * its saved games. It belongs with the rest of the game data rather than
     * in the user profile, so DEFJAM_DATA/save is used when that variable is
     * set -- the same variable the scripts use for the dump. Passing NULL
     * leaves the runtime's own default, %LOCALAPPDATA%\xboxrecomp, which is
     * what an unconfigured checkout gets. No path is hardcoded here: this
     * repository is public and the data lives outside it. */
    {
        extern void xbox_path_init(const char *game_dir, const char *save_dir);
        const char *data = getenv("DEFJAM_DATA");
        char save[512];
        xbox_host_char user_data[MAX_PATH];
        char user_data_utf8[1024];

        if (data && *data) {
            snprintf(save, sizeof(save), "%s%ssave", data,
                     data[strlen(data) - 1] == HOST_SEP_CHAR ? "" : HOST_SEP);
            xbox_path_init(YOUR_GAME_DIR, save);
        } else {
            xbox_path_init(YOUR_GAME_DIR, NULL);
        }
        /* Resolve the same root as all guest file operations, including the
         * runtime's shell-folder fallback. Avoid a second default-path policy. */
#if defined(_WIN32)
        if (xbox_translate_path("\\Device\\Harddisk0\\Partition1\\UDATA", user_data, MAX_PATH)
            && WideCharToMultiByte(CP_UTF8, 0, user_data, -1, user_data_utf8,
                                   sizeof(user_data_utf8), NULL, NULL))
            defjam_save_compat_init(user_data_utf8);
#else
        if (xbox_translate_path("\\Device\\Harddisk0\\Partition1\\UDATA", user_data, MAX_PATH)) {
            snprintf(user_data_utf8, sizeof(user_data_utf8), "%s", user_data);
            defjam_save_compat_init(user_data_utf8);
        }
#endif
        else
            defjam_save_compat_init(NULL);
    }

    /* Step 5: Initialize kernel bridge (thunk table in Xbox memory) */
    printf("Initializing kernel bridge...\n");
    xbox_kernel_bridge_init();

    /* Step 6: Initialize stack */
    g_esp = XBOX_STACK_TOP;

    /*
     * TODO: Pre-initialize CRT globals if needed.
     *
     * Many Xbox games use the MSVC CRT. The CRT's __heap_init sets up a
     * heap descriptor at a game-specific address. You may need to
     * pre-initialize __active_heap to avoid small-block heap issues:
     *
     *   uint32_t *active_heap = (uint32_t *)((uint8_t *)g_xbox_mem_offset + ACTIVE_HEAP_VA);
     *   *active_heap = 1;  // 1 = system heap (HeapAlloc), avoids SBH init
     *
     * Find ACTIVE_HEAP_VA by searching the disassembly for __heap_init
     * or by looking for the CRT's __active_heap global in the data section.
     */

    printf("\n=== Initialization complete ===\n");
    printf("Entry point: 0x%08X\n", YOUR_GAME_ENTRY_POINT);
    printf("ESP: 0x%08X\n", g_esp);

    /* Build the flat dispatch table before the guest runs.
     *
     * Without this recomp_lookup falls back to a binary search over the
     * whole function table -- roughly log2(n) branches on *every*
     * indirect call, which for a 45,000-function C++ title is about 16
     * every time the game goes through a vtable. Half-Life 2 spent most
     * of its static initialisation inside recomp_lookup for exactly this
     * reason, and it read as a hang.
     *
     * Optional by design: if the allocation fails the search still works,
     * so a failure is worth one line and not a fatal error. */
    if (!recomp_dispatch_init())
        fprintf(stderr, "[BOOT] flat dispatch unavailable; "
                        "indirect calls will use the binary search\n");

    /* Arm the hang watchdog. Does nothing unless RECOMP_WATCHDOG_SECS is set,
     * and must be called from this thread -- the guest registers it samples are
     * thread-local, so it has to be handed the copies belonging to the thread
     * that runs guest code.
     *
     * Not optional boilerplate: without this call RECOMP_WATCHDOG_SECS is
     * silently inert, and the one diagnostic that tells a hang from slowness
     * does nothing while appearing to be set. */
    xbox_WatchdogStart();

    /* Step 7: Call the recompiled entry point */
    printf("\nStarting game...\n");
    fflush(stdout);

    /* The title's main thread joins the one host CPU every guest thread
     * shares: the console has one core and this title's movie streamer races
     * without it (toolkit patch 0018, kernel_bridge.c). */
    {
        extern void xbox_PinToGuestCore(void);
#if defined(__APPLE__)
        /* No thread affinity here, so guest threads take turns instead, and
         * one is preempted only while it is in the lifted code. */
        unsigned long size = 0;
        const void *code = getsectiondata(&_mh_execute_header, "__TEXT", "__guest", &size);
        if (code)
            guest_turn_set_code(code, size);
        else
            fprintf(stderr, "[HOST] no guest code section: guest threads change over"
                            " only at kernel calls\n");
#endif
        xbox_PinToGuestCore();
    }
    xbe_entry_point();

    printf("\nGame returned. Cleaning up...\n");

    /* Cleanup */
    xbox_kernel_shutdown();
    xbox_MemoryLayoutShutdown();
    free(xbe_data);

    return 0;
}

/* ── XBE Loading ───────────────────────────────────────────── */

static BOOL load_xbe(const char *path, void **out_data, size_t *out_size)
{
    FILE *f = fopen(path, "rb");
    if (!f) {
        fprintf(stderr, "Cannot open XBE: %s\n", path);
        return FALSE;
    }

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);

    if (size <= 0) {
        fclose(f);
        return FALSE;
    }

    void *data = malloc((size_t)size);
    if (!data) {
        fclose(f);
        return FALSE;
    }

    if (fread(data, 1, (size_t)size, f) != (size_t)size) {
        free(data);
        fclose(f);
        return FALSE;
    }

    fclose(f);
    *out_data = data;
    *out_size = (size_t)size;
    return TRUE;
}

/* Console entry point (for debugging -- lets you see printf output) */
int main(int argc, char **argv)
{
#if defined(_WIN32)
    (void)argc;
    (void)argv;
    return WinMain(GetModuleHandle(NULL), NULL, GetCommandLineA(), SW_SHOW);
#else
    pc_settings_set_args(argc, argv);
    {
        /* The window, if there is one, needs this thread; see host_posix.c. */
        int host_posix_run(int (*game_main)(void));
        return host_posix_run(host_main);
    }
#endif
}
